### PR TITLE
Grab invite a friend window link from User Links API

### PR DESCRIPTION
**Pull request by mumerfarooq000**
**Story Link**
[EDE-528](https://edlyio.atlassian.net/browse/EDE-528)

**Description**
updated the fetching way of invitation url

### CODE REVIEW

**Comment by mumerfarooq000** [comment]
image

I guess the invite friend link is working fine. @danialmalik @mumarkhan999

**Comment by danialmalik** [comment]
@mumarkhan999 do you have any idea about this one? I'm actually seeing this for the first time.
or @tasawernawaz do you know if this is how it should work exactly?

**Comment by tasawernawaz** [comment]
I don't either. I can ask colaraz team to test this.

**Comment by tasawernawaz** [comment]
@mumerfarooq000 colaraz team has tested this, you can merge it now.

**Pull request merged**
